# -*- coding: utf-8 -*-
"""Feature Extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5mM8pINtTBxpIQ6MfLvacpqEgJOvy-w

Install and import the required packages
"""

!pip install pyspark
!pip install keras-core

import librosa
import keras_core
import IPython.display as ipd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pyspark
from google.colab import drive
drive.mount('/content/gdrive')

import os
data_dir = "/content/gdrive/My Drive/Colab Notebooks/Data/genres_original"
genre_dirs = [x[0] for x in os.walk(data_dir)]

filepath_dict = {}
for genre_dir in genre_dirs[1:]:
    filepath_list = []
    for fn in os.listdir(genre_dir):
      filepath_list.append(os.path.join(genre_dir, fn))
      # if fn.endswith(".au"):
      #   filepath_dict[genre_dir.split('/')[-1]] = []

    filepath_dict[genre_dir.split('/')[-1]] = filepath_list

filepath_dict.keys()

y, sr = librosa.load(filepath_dict['classical'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['rock'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['blues'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['disco'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['metal'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['hiphop'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['reggae'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['pop'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['country'][0])
ipd.Audio(y, rate=sr)

y, sr = librosa.load(filepath_dict['jazz'][0])
ipd.Audio(y, rate=sr)

